In [1]:
# Post processing the crossmatched and velocity calculated result
# Merge them into one calatogue and output as a hdf5 file
# Import the libraries
import numpy as np
import pandas as pd
import glob

In [2]:
# Import the data
# for the cm_result, import columns: index, source_id, ra, dec, 
# m_h_ap, m_h_err_ap, m_h_flg_ap, alpha_m_ap, alpha_m_err_ap, alpha_m_flg_ap, 
# m_h_l6s, m_h_err_l6s, m_h_flg_l6s, alpha_m_l6s, alpha_m_err_l6s, alpha_m_flg_l6s,
# m_h_gl3, m_h_err_gl3, m_h_flg_gl3, alpha_m_gl3, alpha_m_err_gl3, alpha_m_flg_gl3,
# m_h_r6, alpha_m_r6, m_h_err_r6, alpha_m_err_r6, XGC, YGC, ZGC
# for the velocity_added, import columns: best_dataset,best_vr,best_vphi,best_vz,
# best_z,best_zerr,best_zqul,best_U,best_V,best_W,best_Uerr,best_Verr,best_Werr,
# best_UVcov,best_UWcov,best_VWcov,best_v_forder_flag

N_files = 16
dir_list = ['dr3_p1_1','dr3_p1_2','dr3_p1_3','dr3_p1_4','dr3_p1_5',
            'dr3_p2_1','dr3_p2_2','dr3_p2_3','dr3_p2_4','dr3_p2_5',
            'dr3_p3_1','dr3_p3_2','dr3_p3_3','dr3_p3_4','dr3_p3_5','dr3_p4']
cm_result_path_list = []
velocity_path_list = []
cm_summary_path_list = []

for i in range(len(dir_list)):
    cm_result_path_list.append('cm_code_paral/'+dir_list[i]+'/cm_result.csv')
    cm_summary_path_list.append('cm_code_paral/'+dir_list[i]+'/cm_summary.csv')
    velocity_file_name = glob.glob('cm_code_paral/'+dir_list[i]+'/velocity_added/best*')[0]
    velocity_path_list.append(velocity_file_name)

In [13]:
cm_columns_to_use = ['index', 'source_id', 'ra', 'dec', 
'm_h_ap', 'm_h_err_ap', 'm_h_flg_ap', 'alpha_m_ap', 'alpha_m_err_ap', 'alpha_m_flg_ap', 
'm_h_l6s', 'm_h_err_l6s', 'm_h_flg_l6s', 'alpha_m_l6s', 'alpha_m_err_l6s', 'alpha_m_flg_l6s',
'm_h_gl3', 'm_h_err_gl3', 'm_h_flg_gl3', 'alpha_m_gl3', 'alpha_m_err_gl3', 'alpha_m_flg_gl3',
'm_h_r6', 'alpha_m_r6', 'm_h_err_r6', 'alpha_m_err_r6', 'XGC', 'YGC', 'ZGC']

velocity_columns_to_use = ['best_dataset','best_vr','best_vphi','best_vz',
'best_z','best_zerr','best_zqul','best_U','best_V','best_W','best_Uerr','best_Verr','best_Werr',
'best_UVcov','best_UWcov','best_VWcov','best_v_forder_flag']

In [27]:
cm_result_list = []
velocity_result_list = []

for i in range(0,N_files):
    print('Appending file #',i)
    cm_result_list.append(pd.read_csv(cm_result_path_list[i],usecols=cm_columns_to_use))
    velocity_result_list.append(pd.read_csv(velocity_path_list[i],usecols=velocity_columns_to_use))
    print(len(cm_result_list[i]),len(velocity_result_list[i]))

Appending file # 0
993396 993396
Appending file # 1
1143586 1143586
Appending file # 2
657237 657237
Appending file # 3
429651 429651
Appending file # 4
431921 431921
Appending file # 5
656010 656010
Appending file # 6
852445 852445
Appending file # 7
692180 692180
Appending file # 8
336114 336114
Appending file # 9
446391 446391
Appending file # 10
421816 421816
Appending file # 11
291562 291562
Appending file # 12
341365 341365
Appending file # 13
357337 357337
Appending file # 14
334008 334008
Appending file # 15
1224595 1224595

In [4]:
cm_summary_list = []

for i in range(0,N_files):
    print('Appending file #',i)
    cm_summary_list.append(pd.read_csv(cm_summary_path_list[i]))
    print(len(cm_summary_list[i]))

Appending file # 0
993396
Appending file # 1
1143586
Appending file # 2
657237
Appending file # 3
429651
Appending file # 4
431921
Appending file # 5
656010
Appending file # 6
852445
Appending file # 7
692180
Appending file # 8
336114
Appending file # 9
446391
Appending file # 10
421816
Appending file # 11
291562
Appending file # 12
341365
Appending file # 13
357337
Appending file # 14
334008
Appending file # 15
1224595

In [28]:
cm_result_all = pd.concat(cm_result_list,axis=0,ignore_index=True)
vel_result_all = pd.concat(velocity_result_list,axis=0,ignore_index=True)

In [5]:
cm_summary_all = pd.concat(cm_summary_list,axis=0,ignore_index=True)

In [31]:
print(len(cm_result_all),len(vel_result_all))

9609614 9609614

In [33]:
print(len(cm_result_all))
vel_result_all.tail()

9609614

,best_dataset,best_vr,best_vphi,best_vz,best_z,best_zerr,best_zqul,best_U,best_V,best_W,best_Uerr,best_Verr,best_Werr,best_UVcov,best_UWcov,best_VWcov,best_v_forder_flag
9609609,SDSSDR16,7.581498,-195.708089,7.633746,-0.000120,7.471827e-06,0.062132,7.554681,195.709126,7.633746,1.477671,1.968099,1.449296,1.037956,-2.015110,-0.326913,0.0
9609610,GaiaDR2,60.026674,-235.578372,-2.025483,-0.000108,8.484890e-06,0.078581,-43.706090,239.144619,-2.025483,1.884865,1.745149,1.451682,1.940995,-0.849599,-2.398162,0.0
9609611,SDSSDR16,-70.355068,-222.322250,23.094880,0.000057,9.502022e-06,0.167049,89.066882,215.508953,23.094880,7.131124,4.779459,2.764231,-27.270719,14.274069,-12.850753,0.0
9609612,SDSSDR16,5.253514,-174.993207,-7.726380,-0.000161,2.037128e-05,0.126241,-2.564970,175.053257,-7.726380,3.548974,4.122926,3.010893,14.162327,-10.423808,-11.061105,0.0
9609613,APOGEE,33.770146,-240.798621,-30.288783,-0.000030,2.195379e-07,0.007431,-28.718174,241.453235,-30.288783,0.160401,0.045713,0.179644,0.000073,0.026307,-0.003053,0.0

In [34]:
# Merge the cm_result with the velocities
cm_velocity_all = pd.concat([cm_result_all, vel_result_all], axis=1)

In [38]:
cm_velocity_all.columns

Index(['index', 'source_id', 'ra', 'dec', 'm_h_ap', 'm_h_err_ap', 'm_h_flg_ap',
       'alpha_m_ap', 'alpha_m_err_ap', 'alpha_m_flg_ap', 'm_h_l6s',
       'm_h_err_l6s', 'm_h_flg_l6s', 'alpha_m_l6s', 'alpha_m_err_l6s',
       'alpha_m_flg_l6s', 'm_h_gl3', 'm_h_err_gl3', 'm_h_flg_gl3',
       'alpha_m_gl3', 'alpha_m_err_gl3', 'alpha_m_flg_gl3', 'm_h_r6',
       'alpha_m_r6', 'm_h_err_r6', 'alpha_m_err_r6', 'XGC', 'YGC', 'ZGC',
       'best_dataset', 'best_vr', 'best_vphi', 'best_vz', 'best_z',
       'best_zerr', 'best_zqul', 'best_U', 'best_V', 'best_W', 'best_Uerr',
       'best_Verr', 'best_Werr', 'best_UVcov', 'best_UWcov', 'best_VWcov',
       'best_v_forder_flag'],
      dtype='object')

In [36]:
# Export the data into hdf5 file
cm_velocity_all.to_hdf('data/dr3_near_good_cm_vel.h5',key='dr3_cm_vel')

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:2505: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block2_values] [items->Index(['best_dataset'], dtype='object')]

  encoding=encoding,

In [6]:
# Export the data into hdf5 file
cm_summary_all.to_hdf('data/dr3_near_good_cm_summary.h5',key='dr3_cm_summary')

In [12]:
# Import data again and append the RAVE cnn metallicity and alpha
cm_vel_all = pd.read_hdf('data/dr3_near_good_cm_vel.h5')
allstar_rave6_df = pd.read_csv('data/ravedr6_param_abuncnn_x_edr3.csv')
cm_summary_all = pd.read_hdf('data/dr3_near_good_cm_summary.h5')

In [8]:
print(len(allstar_rave6_df))

426118

In [14]:
# Unique-fy the RAVEDR6 dataframe
allstar_rave6_unique_df = allstar_rave6_df.drop_duplicates(subset = ["source_id"])

In [9]:
print(len(allstar_rave6_unique_df))

381895

In [4]:
allstar_rave6_unique_df.columns

Index(['rave_obs_id', 'hrv_sparv', 'hrv_error_sparv', 'alpha_m_cnn',
       'alpha_m_error_cnn', 'alpha_m_flag_cnn', 'm_h_cnn', 'm_h_error_cnn',
       'm_h_flag_cnn', 'ra_input', 'dec_input', 'source_id'],
      dtype='object')

In [15]:
# cross match of input stars with RAVE6
# Using pre-matched result
cm_vel_all = cm_vel_all.merge(allstar_rave6_unique_df.loc[:,['source_id','m_h_cnn','alpha_m_cnn',
                                                            'm_h_error_cnn','alpha_m_error_cnn',
                                                            'm_h_flag_cnn','alpha_m_flag_cnn']],
                                                on='source_id',how='left')
cm_vel_all = cm_vel_all.rename(columns={'m_h_cnn':'m_h_r6c','alpha_m_cnn':'alpha_m_r6c',
                                        'm_h_error_cnn':'m_h_err_r6c','alpha_m_error_cnn':'alpha_m_err_r6c',
                                        'm_h_flag_cnn':'m_h_flg_r6c','alpha_m_flag_cnn':'alpha_m_flg_r6c'})

In [20]:
# check the cross match

# RAVE6 all
ind_r6_all = np.where((cm_summary_all.loc[:,'RAVEDR6'] == 1))[0]

# RAVE6 metal+alpha
ind_r6 = np.where((np.isnan(cm_vel_all.loc[:,'m_h_r6']) == False) & 
                  (np.isnan(cm_vel_all.loc[:,'alpha_m_r6']) == False))[0]

# RAVE6 metal
ind_r6_fe = np.where((np.isnan(cm_vel_all.loc[:,'m_h_r6']) == False))[0]

# RAVE6 alpha
ind_r6_alpha = np.where((np.isnan(cm_vel_all.loc[:,'alpha_m_r6']) == False))[0]

# RAVE6 cnn
ind_r6c = np.where((np.isnan(cm_vel_all.loc[:,'m_h_r6c']) == False) & 
                  (np.isnan(cm_vel_all.loc[:,'alpha_m_r6c']) == False))[0]

# RAVE6 cnn metal
ind_r6c_fe = np.where((np.isnan(cm_vel_all.loc[:,'m_h_r6c']) == False))[0]

# RAVE6 cnn alpha
ind_r6c_alpha = np.where((np.isnan(cm_vel_all.loc[:,'alpha_m_r6c']) == False))[0]


print(len(ind_r6_all),len(ind_r6),len(ind_r6c))
print(len(ind_r6_fe),len(ind_r6_alpha))
print(len(ind_r6c_fe),len(ind_r6c_alpha))

366097 221228 318455
234811 304131
318455 318455

In [ ]:
print(len(ind_r6_fe))

In [18]:
print(ind_r6_all[:10],ind_r6[:10],ind_r6c[:10])
print(cm_vel_all.loc[ind_r6_all[:10],'m_h_r6'],cm_vel_all.loc[ind_r6[:10],'m_h_r6'],cm_vel_all.loc[ind_r6c[:10],'m_h_r6'])
print(cm_vel_all.loc[ind_r6_all[:10],'m_h_r6c'],cm_vel_all.loc[ind_r6[:10],'m_h_r6c'],cm_vel_all.loc[ind_r6c[:10],'m_h_r6c'])

[ 44  69 126 176 271 370 413 539 628 734] [  44  176  370  413  628  892  963 1021 1061 1191] [ 44  69 126 176 370 413 539 628 734 761]
44     0.112754
69          NaN
126   -0.151747
176   -0.060825
271         NaN
370    0.053329
413    0.194626
539         NaN
628    0.269988
734         NaN
Name: m_h_r6, dtype: float64 44      0.112754
176    -0.060825
370     0.053329
413     0.194626
628     0.269988
892     0.259159
963     0.040754
1021    0.054786
1061   -0.616452
1191    0.030566
Name: m_h_r6, dtype: float64 44     0.112754
69          NaN
126   -0.151747
176   -0.060825
370    0.053329
413    0.194626
539         NaN
628    0.269988
734         NaN
761         NaN
Name: m_h_r6, dtype: float64
44     0.037098
69    -0.334933
126   -0.082976
176   -0.112023
271         NaN
370    0.007131
413    0.136826
539   -0.318212
628    0.180114
734   -0.118762
Name: m_h_r6c, dtype: float64 44      0.037098
176    -0.112023
370     0.007131
413     0.136826
628     0.180114
892     0.192564
963    -0.050065
1021   -0.027497
1061   -0.497238
1191         NaN
Name: m_h_r6c, dtype: float64 44     0.037098
69    -0.334933
126   -0.082976
176   -0.112023
370    0.007131
413    0.136826
539   -0.318212
628    0.180114
734   -0.118762
761   -0.586729
Name: m_h_r6c, dtype: float64

In [19]:
print(cm_vel_all.loc[ind_r6_all[:10],'alpha_m_r6'])
print(cm_vel_all.loc[ind_r6_all[:10],'alpha_m_r6c'])

44    -0.049336
69     0.698460
126         NaN
176    0.221764
271    0.221125
370    0.138463
413   -0.082908
539    0.483340
628    0.121546
734    0.469028
Name: alpha_m_r6, dtype: float64
44     0.001542
69     0.177998
126    0.094160
176    0.019297
271         NaN
370    0.023001
413   -0.015469
539    0.089043
628   -0.040015
734    0.007052
Name: alpha_m_r6c, dtype: float64

In [21]:
# Export the data into hdf5 file
cm_vel_all.to_hdf('data/dr3_near_good_cm_vel.h5',key='dr3_cm_vel',mode='w')

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:2505: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block2_values] [items->Index(['best_dataset'], dtype='object')]

  encoding=encoding,

In [33]:
# Prepare a file for galactocentric position and velocity calculation using the zero point corrected plx
# Re-Import the data
# for the cm_result, import columns: index, source_id, ra, dec, 
# parallax,parallax_error,pmra,pmra_error,pmdec,pmdec_error,parallax_pmra_corr,parallax_pmdec_corr,
# pmra_pmdec_corr,z_16,zerr_16,z_ap,zerr_ap,
# z_l6s,zerr_l6s,z_gl3,zerr_gl3,
# z_g2,zerr_g2,zqul_g2,zqul_16,zqul_l6s,zqul_ap,zqul_gl3,z_r6,zerr_r6,zqul_r6


cm_columns_to_use = ['index', 'source_id', 'ra', 'dec', 'parallax','parallax_error','pmra','pmra_error','pmdec',
                     'pmdec_error','parallax_pmra_corr','parallax_pmdec_corr','pmra_pmdec_corr','z_16','zerr_16',
                     'z_ap','zerr_ap','z_l6s','zerr_l6s','z_gl3','zerr_gl3','z_g2','zerr_g2','zqul_g2','zqul_16',
                     'zqul_l6s','zqul_ap','zqul_gl3','z_r6','zerr_r6','zqul_r6']

N_files = 16
dir_list = ['dr3_p1_1','dr3_p1_2','dr3_p1_3','dr3_p1_4','dr3_p1_5',
            'dr3_p2_1','dr3_p2_2','dr3_p2_3','dr3_p2_4','dr3_p2_5',
            'dr3_p3_1','dr3_p3_2','dr3_p3_3','dr3_p3_4','dr3_p3_5','dr3_p4']
cm_result_path_list = []

for i in range(len(dir_list)):
    cm_result_path_list.append('cm_code_paral/'+dir_list[i]+'/cm_result.csv')

In [34]:
cm_result_list = []

for i in range(0,N_files):
    print('Appending file #',i)
    cm_result_list.append(pd.read_csv(cm_result_path_list[i],usecols=cm_columns_to_use))
    print(len(cm_result_list[i]))

Appending file # 0
993396
Appending file # 1
1143586
Appending file # 2
657237
Appending file # 3
429651
Appending file # 4
431921
Appending file # 5
656010
Appending file # 6
852445
Appending file # 7
692180
Appending file # 8
336114
Appending file # 9
446391
Appending file # 10
421816
Appending file # 11
291562
Appending file # 12
341365
Appending file # 13
357337
Appending file # 14
334008
Appending file # 15
1224595

In [35]:
cm_result_all = pd.concat(cm_result_list,axis=0,ignore_index=True)

In [25]:
# from the zeropoint correciton: import the zeropoint correction
plxzp_result_all = pd.read_csv('data/dr3_near_good_plxzp_result.csv',usecols=['zero_point_correction'])

In [36]:
print(len(cm_result_all),len(plxzp_result_all))

9609614 9609614

In [37]:
# Merge the cm_result with the zp_correction
cm_plxzp_all = pd.concat([cm_result_all, plxzp_result_all], axis=1)

In [38]:
# Calculate the corrected parallax
cm_plxzp_all['parallax_zpcorr'] = cm_plxzp_all['parallax'] - cm_plxzp_all['zero_point_correction']

In [39]:
cm_plxzp_all.tail()

,index,source_id,ra,dec,parallax,parallax_error,pmra,pmra_error,pmdec,pmdec_error,...,zqul_g2,zqul_16,zqul_l6s,zqul_ap,zqul_gl3,z_r6,zerr_r6,zqul_r6,zero_point_correction,parallax_zpcorr
9609609,30518890,6917522396213398400,315.009523,-0.158389,1.123359,0.056932,0.447019,0.066697,-8.257980,0.035584,...,NaN,0.062132,NaN,NaN,NaN,NaN,NaN,NaN,-0.030829,1.154188
9609610,30518900,6917523053342573568,315.119388,-0.175844,1.254618,0.036933,11.748034,0.041536,4.762686,0.024473,...,0.078581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.038307,1.292925
9609611,30518967,6917526691179095040,314.908073,-0.104466,1.023926,0.110162,-13.512726,0.136268,-11.299918,0.070397,...,NaN,0.167049,NaN,NaN,NaN,NaN,NaN,NaN,-0.032079,1.056005
9609612,30518997,6917527966785173248,314.969944,-0.088191,5.383133,0.111334,21.976828,0.133124,-59.458400,0.069845,...,NaN,0.126241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9609613,30519004,6917528443525529728,314.959247,-0.045324,3.968783,0.016090,46.763742,0.017289,-0.273838,0.010798,...,0.135251,NaN,NaN,0.007431,NaN,NaN,NaN,NaN,-0.022901,3.991684

In [40]:
cm_plxzp_all.columns

Index(['index', 'source_id', 'ra', 'dec', 'parallax', 'parallax_error', 'pmra',
       'pmra_error', 'pmdec', 'pmdec_error', 'parallax_pmra_corr',
       'parallax_pmdec_corr', 'pmra_pmdec_corr', 'z_16', 'zerr_16', 'z_ap',
       'zerr_ap', 'z_l6s', 'zerr_l6s', 'z_gl3', 'zerr_gl3', 'z_g2', 'zerr_g2',
       'zqul_g2', 'zqul_16', 'zqul_l6s', 'zqul_ap', 'zqul_gl3', 'z_r6',
       'zerr_r6', 'zqul_r6', 'zero_point_correction', 'parallax_zpcorr'],
      dtype='object')

In [31]:
# Export the data into hdf5 file
# cm_plxzp_all.to_hdf('data/dr3_near_good_plxzp.h5',key='dr3_cm_plxzp',mode='w')

In [41]:
# Export the data into csv file
cm_plxzp_all.to_csv('data/dr3_near_good_plxzp.csv')

In [51]:
A_test = pd.read_csv('data/dr3_near_good_plxzp.csv',skiprows=range(1,0+1),nrows=10)
A_test

,Unnamed: 0,index,source_id,ra,dec,parallax,parallax_error,pmra,pmra_error,pmdec,...,zqul_g2,zqul_16,zqul_l6s,zqul_ap,zqul_gl3,z_r6,zerr_r6,zqul_r6,zero_point_correction,parallax_zpcorr
0,0,0,34361129088,45.004320,0.021048,3.235017,0.120450,29.518344,0.133693,19.231655,...,NaN,NaN,0.143403,NaN,NaN,NaN,NaN,NaN,-0.036102,3.271119
1,1,1,38655544960,45.004978,0.019880,3.139170,0.022347,29.686339,0.023772,19.115200,...,NaN,NaN,0.096560,NaN,NaN,NaN,NaN,NaN,-0.043019,3.182189
2,2,2,549755818112,45.048282,0.048254,1.583477,0.034425,0.843128,0.038817,-16.443764,...,NaN,NaN,0.107445,NaN,NaN,NaN,NaN,NaN,-0.043406,1.626883
3,3,4,1275606125952,44.993271,0.076334,0.629650,0.048079,-1.435434,0.057797,-6.594886,...,NaN,NaN,0.287529,NaN,NaN,NaN,NaN,NaN,-0.033743,0.663393
4,4,7,1653563247744,44.996062,0.084918,0.301315,0.047155,14.856953,0.056531,-14.749449,...,NaN,NaN,0.079114,NaN,NaN,NaN,NaN,NaN,-0.034288,0.335603
5,5,10,1752346816896,45.005041,0.101934,1.202925,0.234268,9.755676,0.304633,-23.457979,...,NaN,1.515852,NaN,NaN,NaN,NaN,NaN,NaN,-0.021150,1.224075
6,6,11,2851858288640,45.132144,0.137854,2.676207,0.018930,4.722164,0.023343,18.657223,...,0.043555,NaN,0.184713,0.004075,NaN,NaN,NaN,NaN,-0.026364,2.702571
7,7,12,2920577765120,45.164653,0.154500,0.588244,0.037537,-0.327601,0.041943,-13.035882,...,NaN,NaN,0.136844,NaN,NaN,NaN,NaN,NaN,-0.043948,0.632192
8,8,13,2989297243776,45.146386,0.160353,2.358857,0.140653,14.037364,0.168876,-14.364990,...,NaN,0.137808,NaN,NaN,NaN,NaN,NaN,NaN,-0.046009,2.404866
9,9,15,3062312520192,45.116651,0.144720,0.661108,0.041059,17.031780,0.043611,3.631414,...,NaN,NaN,0.061314,NaN,NaN,NaN,NaN,NaN,-0.043957,0.705065

In [54]:
B_test = pd.read_csv('data/dr3_near_good_plxzp.csv',skiprows=range(1,9609610+1),nrows=4)
B_test

,Unnamed: 0,index,source_id,ra,dec,parallax,parallax_error,pmra,pmra_error,pmdec,...,zqul_g2,zqul_16,zqul_l6s,zqul_ap,zqul_gl3,z_r6,zerr_r6,zqul_r6,zero_point_correction,parallax_zpcorr
0,9609610,30518900,6917523053342573568,315.119388,-0.175844,1.254618,0.036933,11.748034,0.041536,4.762686,...,0.078581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.038307,1.292925
1,9609611,30518967,6917526691179095040,314.908073,-0.104466,1.023926,0.110162,-13.512726,0.136268,-11.299918,...,NaN,0.167049,NaN,NaN,NaN,NaN,NaN,NaN,-0.032079,1.056005
2,9609612,30518997,6917527966785173248,314.969944,-0.088191,5.383133,0.111334,21.976828,0.133124,-59.458400,...,NaN,0.126241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9609613,30519004,6917528443525529728,314.959247,-0.045324,3.968783,0.016090,46.763742,0.017289,-0.273838,...,0.135251,NaN,NaN,0.007431,NaN,NaN,NaN,NaN,-0.022901,3.991684

In [2]:
# Combine the velocity and position results from using the zero point corrected plx
# Import the data

cm_columns_to_use = ['index', 'source_id', 'ra', 'dec', 
'm_h_ap', 'm_h_err_ap', 'm_h_flg_ap', 'alpha_m_ap', 'alpha_m_err_ap', 'alpha_m_flg_ap', 
'm_h_l6s', 'm_h_err_l6s', 'm_h_flg_l6s', 'alpha_m_l6s', 'alpha_m_err_l6s', 'alpha_m_flg_l6s',
'm_h_gl3', 'm_h_err_gl3', 'm_h_flg_gl3', 'alpha_m_gl3', 'alpha_m_err_gl3', 'alpha_m_flg_gl3',
'm_h_r6', 'alpha_m_r6', 'm_h_err_r6', 'alpha_m_err_r6']

velocity_columns_to_use = ['best_dataset','best_vr','best_vphi','best_vz',
'best_z','best_zerr','best_zqul','best_U','best_V','best_W','best_Uerr','best_Verr','best_Werr',
'best_UVcov','best_UWcov','best_VWcov','best_v_forder_flag', 'XGC', 'YGC', 'ZGC']

N_files1 = 16
dir_list1 = ['dr3_p1_1','dr3_p1_2','dr3_p1_3','dr3_p1_4','dr3_p1_5',
            'dr3_p2_1','dr3_p2_2','dr3_p2_3','dr3_p2_4','dr3_p2_5',
            'dr3_p3_1','dr3_p3_2','dr3_p3_3','dr3_p3_4','dr3_p3_5','dr3_p4']
cm_result_path_list = []

N_files2 = 10
dir_list2 = ['p1','p2','p3','p4','p5','p6','p7','p8','p9','p10']
vel_path_list = []

for i in range(len(dir_list1)):
    cm_result_path_list.append('cm_code_paral/'+dir_list1[i]+'/cm_result.csv')

for i in range(len(dir_list2)):
    velocity_file_name = glob.glob('vel_calculation_w_plx_corr/'+dir_list2[i]+'/best*')[0]
    vel_path_list.append(velocity_file_name)

In [3]:
cm_result_list = []
vel_result_list = []

for i in range(0,N_files1):
    print('Appending file #',i)
    cm_result_list.append(pd.read_csv(cm_result_path_list[i],usecols=cm_columns_to_use))
    print(len(cm_result_list[i]))
    
for i in range(0,N_files2):
    print('Appending file #',i)
    vel_result_list.append(pd.read_csv(vel_path_list[i],usecols=velocity_columns_to_use))
    print(len(vel_result_list[i]))

Appending file # 0
993396
Appending file # 1
1143586
Appending file # 2
657237
Appending file # 3
429651
Appending file # 4
431921
Appending file # 5
656010
Appending file # 6
852445
Appending file # 7
692180
Appending file # 8
336114
Appending file # 9
446391
Appending file # 10
421816
Appending file # 11
291562
Appending file # 12
341365
Appending file # 13
357337
Appending file # 14
334008
Appending file # 15
1224595
Appending file # 0
1000000
Appending file # 1
1000000
Appending file # 2
1000000
Appending file # 3
1000000
Appending file # 4
1000000
Appending file # 5
1000000
Appending file # 6
1000000
Appending file # 7
1000000
Appending file # 8
1000000
Appending file # 9
609614

In [4]:
cm_result_all = pd.concat(cm_result_list,axis=0,ignore_index=True)
vel_result_all = pd.concat(vel_result_list,axis=0,ignore_index=True)

In [5]:
print(len(cm_result_all),len(vel_result_all))

9609614 9609614

In [6]:
# Merge the cm_result with the velocities
cm_vel_all = pd.concat([cm_result_all, vel_result_all], axis=1)

In [7]:
cm_vel_all.columns

Index(['index', 'source_id', 'ra', 'dec', 'm_h_ap', 'm_h_err_ap', 'm_h_flg_ap',
       'alpha_m_ap', 'alpha_m_err_ap', 'alpha_m_flg_ap', 'm_h_l6s',
       'm_h_err_l6s', 'm_h_flg_l6s', 'alpha_m_l6s', 'alpha_m_err_l6s',
       'alpha_m_flg_l6s', 'm_h_gl3', 'm_h_err_gl3', 'm_h_flg_gl3',
       'alpha_m_gl3', 'alpha_m_err_gl3', 'alpha_m_flg_gl3', 'm_h_r6',
       'alpha_m_r6', 'm_h_err_r6', 'alpha_m_err_r6', 'best_dataset', 'best_vr',
       'best_vphi', 'best_vz', 'XGC', 'YGC', 'ZGC', 'best_z', 'best_zerr',
       'best_zqul', 'best_U', 'best_V', 'best_W', 'best_Uerr', 'best_Verr',
       'best_Werr', 'best_UVcov', 'best_UWcov', 'best_VWcov',
       'best_v_forder_flag'],
      dtype='object')

In [8]:
# Add in the R6C data
allstar_rave6_df = pd.read_csv('data/ravedr6_param_abuncnn_x_edr3.csv')

In [21]:
cm_summary_all = pd.read_hdf('data/dr3_near_good_cm_summary.h5')

In [9]:
# Unique-fy the RAVEDR6 dataframe
allstar_rave6_unique_df = allstar_rave6_df.drop_duplicates(subset = ["source_id"])

In [10]:
print(len(allstar_rave6_unique_df))

381895

In [11]:
allstar_rave6_unique_df.columns

Index(['rave_obs_id', 'hrv_sparv', 'hrv_error_sparv', 'alpha_m_cnn',
       'alpha_m_error_cnn', 'alpha_m_flag_cnn', 'm_h_cnn', 'm_h_error_cnn',
       'm_h_flag_cnn', 'ra_input', 'dec_input', 'source_id'],
      dtype='object')

In [12]:
# cross match of input stars with RAVE6
# Using pre-matched result
cm_vel_all = cm_vel_all.merge(allstar_rave6_unique_df.loc[:,['source_id','m_h_cnn','alpha_m_cnn',
                                                            'm_h_error_cnn','alpha_m_error_cnn',
                                                            'm_h_flag_cnn','alpha_m_flag_cnn']],
                                                on='source_id',how='left')
cm_vel_all = cm_vel_all.rename(columns={'m_h_cnn':'m_h_r6c','alpha_m_cnn':'alpha_m_r6c',
                                        'm_h_error_cnn':'m_h_err_r6c','alpha_m_error_cnn':'alpha_m_err_r6c',
                                        'm_h_flag_cnn':'m_h_flg_r6c','alpha_m_flag_cnn':'alpha_m_flg_r6c'})

In [22]:
# check the cross match

# RAVE6 all
ind_r6_all = np.where((cm_summary_all.loc[:,'RAVEDR6'] == 1))[0]

# RAVE6 metal+alpha
ind_r6 = np.where((np.isnan(cm_vel_all.loc[:,'m_h_r6']) == False) & 
                  (np.isnan(cm_vel_all.loc[:,'alpha_m_r6']) == False))[0]

# RAVE6 metal
ind_r6_fe = np.where((np.isnan(cm_vel_all.loc[:,'m_h_r6']) == False))[0]

# RAVE6 alpha
ind_r6_alpha = np.where((np.isnan(cm_vel_all.loc[:,'alpha_m_r6']) == False))[0]

# RAVE6 cnn
ind_r6c = np.where((np.isnan(cm_vel_all.loc[:,'m_h_r6c']) == False) & 
                  (np.isnan(cm_vel_all.loc[:,'alpha_m_r6c']) == False))[0]

# RAVE6 cnn metal
ind_r6c_fe = np.where((np.isnan(cm_vel_all.loc[:,'m_h_r6c']) == False))[0]

# RAVE6 cnn alpha
ind_r6c_alpha = np.where((np.isnan(cm_vel_all.loc[:,'alpha_m_r6c']) == False))[0]


print(len(ind_r6_all),len(ind_r6),len(ind_r6c))
print(len(ind_r6_fe),len(ind_r6_alpha))
print(len(ind_r6c_fe),len(ind_r6c_alpha))

366097 221228 318455
234811 304131
318455 318455

In [23]:
print(ind_r6_all[:10],ind_r6[:10],ind_r6c[:10])
print(cm_vel_all.loc[ind_r6_all[:10],'m_h_r6'],cm_vel_all.loc[ind_r6[:10],'m_h_r6'],cm_vel_all.loc[ind_r6c[:10],'m_h_r6'])
print(cm_vel_all.loc[ind_r6_all[:10],'m_h_r6c'],cm_vel_all.loc[ind_r6[:10],'m_h_r6c'],cm_vel_all.loc[ind_r6c[:10],'m_h_r6c'])

[ 44  69 126 176 271 370 413 539 628 734] [  44  176  370  413  628  892  963 1021 1061 1191] [ 44  69 126 176 370 413 539 628 734 761]
44     0.112754
69          NaN
126   -0.151747
176   -0.060825
271         NaN
370    0.053329
413    0.194626
539         NaN
628    0.269988
734         NaN
Name: m_h_r6, dtype: float64 44      0.112754
176    -0.060825
370     0.053329
413     0.194626
628     0.269988
892     0.259159
963     0.040754
1021    0.054786
1061   -0.616452
1191    0.030566
Name: m_h_r6, dtype: float64 44     0.112754
69          NaN
126   -0.151747
176   -0.060825
370    0.053329
413    0.194626
539         NaN
628    0.269988
734         NaN
761         NaN
Name: m_h_r6, dtype: float64
44     0.037098
69    -0.334933
126   -0.082976
176   -0.112023
271         NaN
370    0.007131
413    0.136826
539   -0.318212
628    0.180114
734   -0.118762
Name: m_h_r6c, dtype: float64 44      0.037098
176    -0.112023
370     0.007131
413     0.136826
628     0.180114
892     0.192564
963    -0.050065
1021   -0.027497
1061   -0.497238
1191         NaN
Name: m_h_r6c, dtype: float64 44     0.037098
69    -0.334933
126   -0.082976
176   -0.112023
370    0.007131
413    0.136826
539   -0.318212
628    0.180114
734   -0.118762
761   -0.586729
Name: m_h_r6c, dtype: float64

In [24]:
print(cm_vel_all.loc[ind_r6_all[:10],'alpha_m_r6'])
print(cm_vel_all.loc[ind_r6_all[:10],'alpha_m_r6c'])

44    -0.049336
69     0.698460
126         NaN
176    0.221764
271    0.221125
370    0.138463
413   -0.082908
539    0.483340
628    0.121546
734    0.469028
Name: alpha_m_r6, dtype: float64
44     0.001542
69     0.177998
126    0.094160
176    0.019297
271         NaN
370    0.023001
413   -0.015469
539    0.089043
628   -0.040015
734    0.007052
Name: alpha_m_r6c, dtype: float64

In [25]:
# Export the data into hdf5 file
# cm_vel_all.to_hdf('data/dr3_near_good_cm_vel_plxzp.h5',key='dr3_cm_vel_plxzp',mode='w')

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:2505: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block2_values] [items->Index(['best_dataset'], dtype='object')]

  encoding=encoding,

In [2]:
# Group together the orbital parameter results
# Get the file paths
N_files = 10
dir_list = ['p1','p2','p3','p4','p5','p6','p7','p8','p9','p10']
orb_path_list = []

for i in range(len(dir_list)):
    orb_file_name = glob.glob('orbit_int_paral/'+dir_list[i]+'/orb*')[0]
    orb_path_list.append(orb_file_name)

In [3]:
# import the data
orb_result_list = []

for i in range(0,N_files):
    print('Appending file #',i)
    orb_result_list.append(pd.read_csv(orb_path_list[i]))
    print(len(orb_result_list[i]))

Appending file # 0
1000000
Appending file # 1
1000000
Appending file # 2
1000000
Appending file # 3
1000000
Appending file # 4
1000000
Appending file # 5
1000000
Appending file # 6
1000000
Appending file # 7
1000000
Appending file # 8
1000000
Appending file # 9
609614

In [4]:
orb_result_all = pd.concat(orb_result_list,axis=0,ignore_index=True)

In [5]:
len(orb_result_all)

9609614

In [6]:
# Export the data into hdf5 file
orb_result_all.to_hdf('data/dr3_near_good_cm_orb_param.h5',key='dr3_cm_orb',mode='w')

In [10]:
# Include the quality flags to the cross-matched plx zp corrected velocity hdf5 file
# Import the cross-matched gaia sample with all the quality indicators
file_path = 'data/dr3_near_good_cm_qual_plxzp.csv'
df = pd.read_csv(file_path)

# Import the cross-matched gaia sample with the velocities
file_path = 'data/dr3_near_good_cm_vel_plxzp.h5'
df_vel = pd.read_hdf(file_path)

In [12]:
print(len(df),len(df_vel))

9609614 9609614

In [15]:
# Generate the flags
# Prepare some columns
df['distance'] = 1/(df.parallax-df.zero_point_correction)
df['G'] = df.phot_g_mean_mag

# For the calibrated color factor
# use the expression in Riello et al. (2021)
def f_GBP_GRP(Bp,Rp):
    x = Bp-Rp
    if x < 0.5:
        f = 1.154360+0.033772*x+0.032277*x**2
    elif x >= 0.5 and x < 4.0:
        f = 1.162004+0.011464*x+0.049255*x**2-0.005879*x**3
    elif x >= 4.0:
        f = 1.057572+0.140537*x
    else:
        f = np.nan
    return f

df['color'] = df.phot_bp_mean_mag-df.phot_rp_mean_mag

df['C_cal'] = np.nan
ind_color_tmp = np.where(df.color < 0.5)[0]
df.loc[ind_color_tmp,'C_cal'] = df.loc[ind_color_tmp,'phot_bp_rp_excess_factor'] - (1.154360+0.033772*df.color+0.032277*df.color**2)
ind_color_tmp = np.where((df.color >= 0.5) & (df.color < 4.0))[0]
df.loc[ind_color_tmp,'C_cal'] = df.loc[ind_color_tmp,'phot_bp_rp_excess_factor'] - (1.162004+0.011464*df.color+0.049255*df.color**2-0.005879*df.color**3)
ind_color_tmp = np.where((df.color >= 4.0))[0]
df.loc[ind_color_tmp,'C_cal'] = df.loc[ind_color_tmp,'phot_bp_rp_excess_factor'] - (1.057572+0.140537*df.color)

df['sig_C_cal'] = 0.0059898 + 8.817481*10**(-12)*df.phot_g_mean_mag**(7.618399)

In [17]:
# List the cuts
# Keep in mind that the poe > 5 cut and the ruew < 1.4 cut are already applied to the sample
science = (df.parallax_over_error > 5) & (df.distance < 5) 
general = (df.duplicated_source == 0) & (df.visibility_periods_used >= 10)
magnitude = (df.G < 19) #& (df.phot_g_mean_flux_over_error > 2000)
astrometric = (df.astrometric_excess_noise < 2) & (df.ruwe < 1.4)
binary_exclusion = (df.ipd_frac_multi_peak <= 2) & (df.ipd_gof_harmonic_amplitude < np.exp(0.18*(df.G-33)))
photometry = (abs(df.C_cal/df.sig_C_cal) < 3)
rv_dr2 = (abs(df.dr2_radial_velocity) >= 0)

In [28]:
ind_qual_gd = np.where(science & astrometric & general & magnitude & photometry)[0]
ind_bin_gd = np.where(binary_exclusion)[0]
ind_tmp = np.where(science & astrometric & general & magnitude & photometry & binary_exclusion)[0]
print(len(ind_qual_gd),len(ind_bin_gd),len(ind_tmp))

8875658 6326282 5896388

In [29]:
df_vel['qual_flag'] = 1
df_vel['bin_flag'] = 1

df_vel.loc[ind_qual_gd,'qual_flag'] = 0
df_vel.loc[ind_bin_gd,'bin_flag'] = 0

In [24]:
df

,source_id,parallax,parallax_over_error,ruwe,astrometric_gof_al,astrometric_excess_noise,duplicated_source,phot_g_mean_mag,phot_g_mean_flux_over_error,visibility_periods_used,...,phot_bp_rp_excess_factor,phot_bp_mean_mag,phot_rp_mean_mag,dr2_radial_velocity,zero_point_correction,distance,G,C_cal,color,sig_C_cal
0,34361129088,3.235017,26.857704,1.057890,1.081467,0.267413,False,17.571619,831.2096,15,...,1.456570,18.860890,16.402643,NaN,-0.036102,0.305706,17.571619,0.056071,2.458247,0.032832
1,38655544960,3.139170,140.471310,1.012191,0.264343,0.000000,False,14.128453,3689.2130,15,...,1.242403,14.703050,13.410816,NaN,-0.043019,0.314249,14.128453,-0.003978,1.292234,0.011086
2,549755818112,1.583477,45.997280,1.090977,1.736130,0.072145,False,14.987767,2908.7566,13,...,1.244187,15.536090,14.281755,NaN,-0.043406,0.614672,14.987767,0.001909,1.254335,0.013980
3,1275606125952,0.629650,13.096099,1.009844,0.229485,0.067907,False,16.236270,1596.2009,15,...,1.215624,16.662441,15.644692,NaN,-0.033743,1.507402,16.236270,-0.002869,1.017749,0.020690
4,1653563247744,0.301315,6.389830,1.030815,0.637752,0.099842,False,16.148806,1756.5657,16,...,1.203869,16.436014,15.681716,NaN,-0.034288,2.979709,16.148806,0.007716,0.754298,0.020097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9609609,6917522396213398400,1.123359,19.731644,0.963490,-1.020787,0.000000,False,16.109600,2356.5215,15,...,1.240288,16.649828,15.413288,NaN,-0.030829,0.866410,16.109600,-0.000089,1.236540,0.019838
9609610,6917523053342573568,1.254618,33.970074,1.296534,7.243706,0.191588,True,13.033514,2522.2270,15,...,1.196894,13.334305,12.566516,-32.370556,-0.038307,0.773440,13.033514,-0.000286,0.767789,0.008746
9609611,6917526691179095040,1.023926,9.294751,1.022214,0.664459,0.000000,False,17.373154,1310.3745,15,...,1.273238,18.114988,16.539637,NaN,-0.032079,0.946965,17.373154,-0.006079,1.575351,0.030607
9609612,6917527966785173248,5.383133,48.351173,0.957177,-1.280572,0.200776,False,17.394567,1245.1193,15,...,1.603199,18.632511,16.112263,NaN,NaN,NaN,17.394567,0.193562,2.520248,0.030839
9609613,6917528443525529728,3.968783,246.663280,0.930465,-2.067335,0.045040,False,12.606441,6670.0537,16,...,1.210101,13.024818,12.028488,-8.344880,-0.022901,0.250521,12.606441,-0.006404,0.996330,0.008128

In [30]:
df_vel

,index,source_id,ra,dec,m_h_ap,m_h_err_ap,m_h_flg_ap,alpha_m_ap,alpha_m_err_ap,alpha_m_flg_ap,...,best_VWcov,best_v_forder_flag,m_h_r6c,alpha_m_r6c,m_h_err_r6c,alpha_m_err_r6c,m_h_flg_r6c,alpha_m_flg_r6c,qual_flag,bin_flag
0,0,34361129088,45.004320,0.021048,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.074983,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0,0
1,1,38655544960,45.004978,0.019880,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.451130,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0,0
2,2,549755818112,45.048282,0.048254,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.045706,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0,0
3,4,1275606125952,44.993271,0.076334,NaN,NaN,NaN,NaN,NaN,NaN,...,1.920111,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0,0
4,7,1653563247744,44.996062,0.084918,NaN,NaN,NaN,NaN,NaN,NaN,...,-29.369785,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9609609,30518890,6917522396213398400,315.009523,-0.158389,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.452717,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0,0
9609610,30518900,6917523053342573568,315.119388,-0.175844,NaN,NaN,NaN,NaN,NaN,NaN,...,-2.358347,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1,1
9609611,30518967,6917526691179095040,314.908073,-0.104466,NaN,NaN,NaN,NaN,NaN,NaN,...,-11.628281,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0,0
9609612,30518997,6917527966785173248,314.969944,-0.088191,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
9609613,30519004,6917528443525529728,314.959247,-0.045324,-0.072642,0.011782,0.0,0.025962,0.007939,NaN,...,-0.003017,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0,1

In [31]:
# Export the data into hdf5 file
df_vel.to_hdf('data/dr3_near_good_cm_vel_plxzp.h5',key='dr3_cm_vel_plxzp',mode='w')

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:2505: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block2_values] [items->Index(['best_dataset'], dtype='object')]

  encoding=encoding,

In [22]:
# Include the plx_zp and its errors to the cross-matched plx zp corrected velocity hdf5 file
# Import the cross-matched gaia sample with the parallax and errors
file_path = 'data/dr3_near_good_plxzp.csv'
df_plx = pd.read_csv(file_path,usecols=['parallax','parallax_error','parallax_zpcorr'])

# Import the cross-matched gaia sample with the l and b
file_path = 'data/dr3_near_good_cm_lb.csv'
df_lb = pd.read_csv(file_path,usecols=['l','b'])

# Import the cross-matched gaia sample with the velocities
file_path = 'data/dr3_near_good_cm_vel_plxzp.h5'
df_vel = pd.read_hdf(file_path)

In [23]:
# Merge the parallax with the velocities
df_vel = pd.concat([df_vel, df_plx, df_lb], axis=1)

In [43]:
print(df_vel.columns)
print(len(df_vel))

Index(['index', 'source_id', 'ra', 'dec', 'm_h_ap', 'm_h_err_ap', 'm_h_flg_ap',
       'alpha_m_ap', 'alpha_m_err_ap', 'alpha_m_flg_ap', 'm_h_l6s',
       'm_h_err_l6s', 'm_h_flg_l6s', 'alpha_m_l6s', 'alpha_m_err_l6s',
       'alpha_m_flg_l6s', 'm_h_gl3', 'm_h_err_gl3', 'm_h_flg_gl3',
       'alpha_m_gl3', 'alpha_m_err_gl3', 'alpha_m_flg_gl3', 'm_h_r6',
       'alpha_m_r6', 'm_h_err_r6', 'alpha_m_err_r6', 'best_dataset', 'best_vr',
       'best_vphi', 'best_vz', 'XGC', 'YGC', 'ZGC', 'best_z', 'best_zerr',
       'best_zqul', 'best_U', 'best_V', 'best_W', 'best_Uerr', 'best_Verr',
       'best_Werr', 'best_UVcov', 'best_UWcov', 'best_VWcov',
       'best_v_forder_flag', 'm_h_r6c', 'alpha_m_r6c', 'm_h_err_r6c',
       'alpha_m_err_r6c', 'm_h_flg_r6c', 'alpha_m_flg_r6c', 'qual_flag',
       'bin_flag', 'parallax', 'parallax_error', 'parallax_zpcorr', 'l', 'b'],
      dtype='object')
9609614

In [21]:
A = uncertainties.ufloat(np.nan, np.nan)
print(A)

nan+/-nan

In [35]:
import uncertainties
from uncertainties import unumpy
import astropy.coordinates as coord
coord.galactocentric_frame_defaults.set('v4.0')
print(coord.Galactocentric())

def celes_to_gc_coord_err(l,b,plx,plx_err):
    '''
    Input units as before
    Output coordinates are in pc
    '''
    rSun = 8122 #pc
    x_shift = -rSun
    y_shift = 0.
    z_shift = 20.8 #pc
    
    plx_u = uncertainties.ufloat(plx, plx_err)
    d_u = 1/plx_u*1000 #pc
    
    x_u = d_u * np.cos(np.radians(b)) * np.cos(np.radians(l)) + x_shift
    y_u = d_u * np.cos(np.radians(b)) * np.sin(np.radians(l)) + y_shift
    z_u = d_u * np.sin(np.radians(b)) + z_shift 
    
    x = unumpy.nominal_values(x_u)
    y = unumpy.nominal_values(y_u)
    z = unumpy.nominal_values(z_u)
    
    x_err = unumpy.std_devs(x_u)
    y_err = unumpy.std_devs(y_u)
    z_err = unumpy.std_devs(z_u)
    
    return x, y, z, x_err, y_err, z_err

<Galactocentric Frame (galcen_coord=<ICRS Coordinate: (ra, dec) in deg
    (266.4051, -28.936175)>, galcen_distance=8.122 kpc, galcen_v_sun=(12.9, 245.6, 7.78) km / s, z_sun=20.8 pc, roll=0.0 deg)>

In [39]:
# Calculate the positions and errors
x_tmp = np.zeros(len(df_vel))
y_tmp = np.zeros(len(df_vel))
z_tmp = np.zeros(len(df_vel))

xerr_tmp = np.zeros(len(df_vel))
yerr_tmp = np.zeros(len(df_vel))
zerr_tmp = np.zeros(len(df_vel))

l_tmp = df_vel['l'].values
b_tmp = df_vel['b'].values
plx_tmp = df_vel['parallax_zpcorr'].values
plxerr_tmp = df_vel['parallax_error'].values

for i in range(len(df_vel)):
# for i in range(20):
    x_tmp[i], y_tmp[i], z_tmp[i], xerr_tmp[i], yerr_tmp[i], zerr_tmp[i] = celes_to_gc_coord_err(l_tmp[i],b_tmp[i],plx_tmp[i],plxerr_tmp[i])
    if i%100000 == 0:
        print(i,'stars finished.')

0 stars finished.
100000 stars finished.
200000 stars finished.
300000 stars finished.
400000 stars finished.
500000 stars finished.
600000 stars finished.
700000 stars finished.
800000 stars finished.
900000 stars finished.
1000000 stars finished.
1100000 stars finished.
1200000 stars finished.
1300000 stars finished.
1400000 stars finished.
1500000 stars finished.
1600000 stars finished.
1700000 stars finished.
1800000 stars finished.
1900000 stars finished.
2000000 stars finished.
2100000 stars finished.
2200000 stars finished.
2300000 stars finished.
2400000 stars finished.
2500000 stars finished.
2600000 stars finished.
2700000 stars finished.
2800000 stars finished.
2900000 stars finished.
3000000 stars finished.
3100000 stars finished.
3200000 stars finished.
3300000 stars finished.
3400000 stars finished.
3500000 stars finished.
3600000 stars finished.
3700000 stars finished.
3800000 stars finished.
3900000 stars finished.
4000000 stars finished.
4100000 stars finished.
4200000 stars finished.
4300000 stars finished.
4400000 stars finished.
4500000 stars finished.
4600000 stars finished.
4700000 stars finished.
4800000 stars finished.
4900000 stars finished.
5000000 stars finished.
5100000 stars finished.
5200000 stars finished.
5300000 stars finished.
5400000 stars finished.
5500000 stars finished.
5600000 stars finished.
5700000 stars finished.
5800000 stars finished.
5900000 stars finished.
6000000 stars finished.
6100000 stars finished.
6200000 stars finished.
6300000 stars finished.
6400000 stars finished.
6500000 stars finished.
6600000 stars finished.
6700000 stars finished.
6800000 stars finished.
6900000 stars finished.
7000000 stars finished.
7100000 stars finished.
7200000 stars finished.
7300000 stars finished.
7400000 stars finished.
7500000 stars finished.
7600000 stars finished.
7700000 stars finished.
7800000 stars finished.
7900000 stars finished.
8000000 stars finished.
8100000 stars finished.
8200000 stars finished.
8300000 stars finished.
8400000 stars finished.
8500000 stars finished.
8600000 stars finished.
8700000 stars finished.
8800000 stars finished.
8900000 stars finished.
9000000 stars finished.
9100000 stars finished.
9200000 stars finished.
9300000 stars finished.
9400000 stars finished.
9500000 stars finished.
9600000 stars finished.

In [40]:
def get_vel_cyl(**kwargs):
    # Create the astropy sample
    samples = coord.SkyCoord(**kwargs)
    vtot = np.sqrt(samples.v_x.to_value(u.km/u.s)**2+samples.v_y.to_value(u.km/u.s)**2+samples.v_z.to_value(u.km/u.s)**2)
    samples.representation_type = 'cylindrical'
    
    return samples.d_rho.to_value(u.km/u.s), samples.d_phi.to_value(u.rad/u.s)*samples.rho.to_value(u.km), samples.d_z.to_value(u.km/u.s)

In [42]:
import astropy.units as u
import astropy.coordinates as coord
coord.galactocentric_frame_defaults.set('v4.0')
df_vel['best_vr'], df_vel['best_vphi'], df_vel['best_vz'] = get_vel_cyl(x=x_tmp*u.pc, y=y_tmp*u.pc, z=z_tmp*u.pc, 
                                                                        v_x=df_vel['best_U'].values*u.km/u.second, v_y=df_vel['best_V'].values*u.km/u.second, v_z=df_vel['best_W'].values*u.km/u.second, frame=coord.Galactocentric)

In [38]:
# Check that the numbers are not terribly off from the astropy result
print(x_tmp[0:20],y_tmp[0:20],z_tmp[0:20],xerr_tmp[0:20],yerr_tmp[0:20],zerr_tmp[0:20])
print(df_vel.loc[0:19,['XGC','YGC','ZGC']])

[ -8322.73786738  -8328.34672264  -8526.03086003  -9112.35145104
 -10079.94502754  -8658.99861865  -8365.80919448  -9165.00472804
  -8396.12932356  -9056.40120984  -8489.48548799  -8664.68034033
  -9440.1400269   -8728.12156459  -9002.09894099  -9145.49848894
  -9314.38075555  -8331.29268655  -8758.10043396  -8227.07109567] [ 10.72122947  11.01366539  21.46169799  54.14469982 107.26584398
  29.50516072  12.99202648  55.28720149  14.65367135  50.18112802
  20.00991005  29.7656067   73.36265504  34.6798264   50.7427014
  60.16222786  68.79121783  12.1061396   36.3376531    5.89097839] [ -209.51581575  -215.953486    -441.93162481 -1114.33590706
 -2222.77068686  -594.14548174  -257.23177015 -1167.12690995
  -291.52610256 -1045.02301706  -399.18795869  -599.17733965
 -1483.04651     -675.12398448  -990.11182831 -1153.48134398
 -1345.37623334  -218.81236711  -706.72849464   -99.02075727] [  7.39163702   1.4491015    8.54944339  71.77541277 275.10987121
 102.77259717   1.7077072   61.92915443  16.03291339  54.41393617
   3.21462485  13.34825981 117.50334786  10.85883395  57.67543773
 151.87391496 103.74870755   1.13889312  11.70879773   0.33679182] [ 0.3947807   0.07734515  0.45413752  3.92412025 15.0718698   5.64679664
  0.09099976  3.28271728  0.85704455  2.92224867  0.17503917  0.73214197
  6.53978894  0.62129859  3.32531648  8.92729513  5.98550413  0.06587712
  0.66887272  0.01888277] [  8.48076615   1.66263766   9.79157342  82.2686211  315.24298896
 117.69032932   1.94741161  70.53401301  18.26691609  62.06715596
   3.67389672  15.24952719 134.05783603  12.46766891  66.24798587
 174.24813705 118.87060222   1.30388157  13.39172799   0.38406995]
             XGC         YGC          ZGC
0   -8323.300075   10.721737  -209.001244
1   -8328.925390   11.014187  -215.424536
2   -8527.187276   21.462718  -440.895934
3   -9115.226982   54.147201 -1111.797240
4  -10085.654456  107.270788 -2217.751692
5   -8660.544194   29.506516  -592.768941
6   -8366.493392   12.992640  -256.606795
7   -9168.015208   55.289824 -1164.453299
8   -8396.901198   14.654361  -290.823406
9   -9059.099517   50.183480 -1042.627791
10  -8490.532620   20.010836  -398.245950
11  -8666.238776   29.766974  -597.786239
12  -9443.958207   73.365974 -1479.667610
13  -8729.874179   34.681359  -673.570246
14  -9004.656876   50.744927  -987.855771
15  -9148.474102   60.164814 -1150.857698
16  -9317.846975   68.794228 -1342.319680
17  -8331.878660   12.106668  -218.275866
18  -8759.933843   36.339257  -705.097917
19  -8227.350802    5.891243   -98.751420

In [44]:
# Assign the new position and errors to the dataframe
df_vel['XGC'], df_vel['YGC'], df_vel['ZGC'] = x_tmp, y_tmp, z_tmp

In [45]:
df_vel['XGCerr'], df_vel['YGCerr'], df_vel['ZGCerr'] = xerr_tmp, yerr_tmp, zerr_tmp

In [46]:
print(df_vel.columns)

Index(['index', 'source_id', 'ra', 'dec', 'm_h_ap', 'm_h_err_ap', 'm_h_flg_ap',
       'alpha_m_ap', 'alpha_m_err_ap', 'alpha_m_flg_ap', 'm_h_l6s',
       'm_h_err_l6s', 'm_h_flg_l6s', 'alpha_m_l6s', 'alpha_m_err_l6s',
       'alpha_m_flg_l6s', 'm_h_gl3', 'm_h_err_gl3', 'm_h_flg_gl3',
       'alpha_m_gl3', 'alpha_m_err_gl3', 'alpha_m_flg_gl3', 'm_h_r6',
       'alpha_m_r6', 'm_h_err_r6', 'alpha_m_err_r6', 'best_dataset', 'best_vr',
       'best_vphi', 'best_vz', 'XGC', 'YGC', 'ZGC', 'best_z', 'best_zerr',
       'best_zqul', 'best_U', 'best_V', 'best_W', 'best_Uerr', 'best_Verr',
       'best_Werr', 'best_UVcov', 'best_UWcov', 'best_VWcov',
       'best_v_forder_flag', 'm_h_r6c', 'alpha_m_r6c', 'm_h_err_r6c',
       'alpha_m_err_r6c', 'm_h_flg_r6c', 'alpha_m_flg_r6c', 'qual_flag',
       'bin_flag', 'parallax', 'parallax_error', 'parallax_zpcorr', 'l', 'b',
       'XGCerr', 'YGCerr', 'ZGCerr'],
      dtype='object')

In [47]:
print(df_vel.loc[0:10,['XGC','YGC','ZGC','XGCerr','YGCerr','ZGCerr']])

             XGC         YGC          ZGC      XGCerr     YGCerr      ZGCerr
0   -8322.737867   10.721229  -209.515816    7.391637   0.394781    8.480766
1   -8328.346723   11.013665  -215.953486    1.449101   0.077345    1.662638
2   -8526.030860   21.461698  -441.931625    8.549443   0.454138    9.791573
3   -9112.351451   54.144700 -1114.335907   71.775413   3.924120   82.268621
4  -10079.945028  107.265844 -2222.770687  275.109871  15.071870  315.242989
5   -8658.998619   29.505161  -594.145482  102.772597   5.646797  117.690329
6   -8365.809194   12.992026  -257.231770    1.707707   0.091000    1.947412
7   -9165.004728   55.287201 -1167.126910   61.929154   3.282717   70.534013
8   -8396.129324   14.653671  -291.526103   16.032913   0.857045   18.266916
9   -9056.401210   50.181128 -1045.023017   54.413936   2.922249   62.067156
10  -8489.485488   20.009910  -399.187959    3.214625   0.175039    3.673897

In [48]:
# Export the data into hdf5 file
df_vel.to_hdf('data/dr3_near_good_cm_vel_plxzp.h5',key='dr3_cm_vel_plxzp',mode='w')

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:2505: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block2_values] [items->Index(['best_dataset'], dtype='object')]

  encoding=encoding,

In [50]:
# Export just the position and velocities for action calculation
df_vel.to_csv('data/dr3_near_good_cm_velpos_only.csv',index=False,columns=['source_id','XGC','YGC','ZGC','best_U','best_V','best_W'])